In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv('owid-covid-data.csv')
data.head()

  iso_code continent  ... human_development_index excess_mortality
0      AFG      Asia  ...                   0.511              NaN
1      AFG      Asia  ...                   0.511              NaN
2      AFG      Asia  ...                   0.511              NaN
3      AFG      Asia  ...                   0.511              NaN
4      AFG      Asia  ...                   0.511              NaN

[5 rows x 60 columns]

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101998 entries, 0 to 101997
Data columns (total 60 columns):
 #   Column                                 Non-Null Count   Dtype
---  ------                                 --------------   -----
 0   iso_code                               101998 non-null  object
 1   continent                              97230 non-null   object
 2   location                               101998 non-null  object
 3   date                                   101998 non-null  object
 4   total_cases                            98192 non-null   float64
 5   new_cases                              98189 non-null   float64
 6   new_cases_smoothed                     97179 non-null   float64
 7   total_deaths                           87983 non-null   float64
 8   new_deaths                             88139 non-null   float64
 9   new_deaths_smoothed                    97179 non-null   float64
 10  total_cases_per_million                97670 non-null   float64
 11  new_cases_per_million                  97667 non-null   float64
 12  new_cases_smoothed_per_million         96662 non-null   float64
 13  total_deaths_per_million               87474 non-null   float64
 14  new_deaths_per_million                 87630 non-null   float64
 15  new_deaths_smoothed_per_million        96662 non-null   float64
 16  reproduction_rate                      82227 non-null   float64
 17  icu_patients                           10257 non-null   float64
 18  icu_patients_per_million               10257 non-null   float64
 19  hosp_patients                          12736 non-null   float64
 20  hosp_patients_per_million              12736 non-null   float64
 21  weekly_icu_admissions                  928 non-null     float64
 22  weekly_icu_admissions_per_million      928 non-null     float64
 23  weekly_hosp_admissions                 1591 non-null    float64
 24  weekly_hosp_admissions_per_million     1591 non-null    float64
 25  new_tests                              45517 non-null   float64
 26  total_tests                            45185 non-null   float64
 27  total_tests_per_thousand               45185 non-null   float64
 28  new_tests_per_thousand                 45517 non-null   float64
 29  new_tests_smoothed                     52971 non-null   float64
 30  new_tests_smoothed_per_thousand        52971 non-null   float64
 31  positive_rate                          49510 non-null   float64
 32  tests_per_case                         48912 non-null   float64
 33  tests_units                            54656 non-null   object
 34  total_vaccinations                     17814 non-null   float64
 35  people_vaccinated                      16964 non-null   float64
 36  people_fully_vaccinated                14088 non-null   float64
 37  new_vaccinations                       14839 non-null   float64
 38  new_vaccinations_smoothed              31080 non-null   float64
 39  total_vaccinations_per_hundred         17814 non-null   float64
 40  people_vaccinated_per_hundred          16964 non-null   float64
 41  people_fully_vaccinated_per_hundred    14088 non-null   float64
 42  new_vaccinations_smoothed_per_million  31080 non-null   float64
 43  stringency_index                       85561 non-null   float64
 44  population                             101342 non-null  float64
 45  population_density                     94735 non-null   float64
 46  median_age                             91054 non-null   float64
 47  aged_65_older                          90032 non-null   float64
 48  aged_70_older                          90551 non-null   float64
 49  gdp_per_capita                         91423 non-null   float64
 50  extreme_poverty                        61663 non-null   float64
 51  cardiovasc_death_rate                  91428 non-null   float64
 52  diabetes_prevalence                    93811 non-null   float64
 53  female_smokers                         71488 non-null   float64
 54  male_smokers                           70445 non-null   float64
 55  handwashing_facilities                 45943 non-null   float64
 56  hospital_beds_per_thousand             83260 non-null   float64
 57  life_expectancy                        96855 non-null   float64
 58  human_development_index                91566 non-null   float64
 59  excess_mortality                       3571 non-null    float64
dtypes: float64(55), object(5)
memory usage: 46.7+ MB

In [ ]:
data.describe()

        total_cases      new_cases  ...  human_development_index  excess_mortality
count  9.819200e+04   98189.000000  ...             91566.000000       3571.000000
mean   1.105663e+06    6046.976790  ...                 0.727228         18.251563
std    7.548017e+06   37688.281473  ...                 0.150349         35.848993
min    1.000000e+00  -74347.000000  ...                 0.394000        -95.590000
25%    1.337000e+03       2.000000  ...                 0.602000          0.450000
50%    1.409300e+04      74.000000  ...                 0.748000          7.390000
75%    1.508630e+05     820.000000  ...                 0.848000         23.995000
max    1.872385e+08  906017.000000  ...                 0.957000        409.760000

[8 rows x 55 columns]

In [ ]:
# Filter malaysia only
data.loc[data['location'] == 'Malaysia']

      iso_code continent  ... human_development_index excess_mortality
56108      MYS      Asia  ...                    0.81              NaN
56109      MYS      Asia  ...                    0.81              NaN
56110      MYS      Asia  ...                    0.81              NaN
56111      MYS      Asia  ...                    0.81              NaN
56112      MYS      Asia  ...                    0.81              NaN
...        ...       ...  ...                     ...              ...
56638      MYS      Asia  ...                    0.81              NaN
56639      MYS      Asia  ...                    0.81              NaN
56640      MYS      Asia  ...                    0.81              NaN
56641      MYS      Asia  ...                    0.81              NaN
56642      MYS      Asia  ...                    0.81              NaN

[535 rows x 60 columns]

In [ ]:
# X - date
# y - New cases (nak predict new daily cases)

In [ ]:
# See correlation of data
torr = data.corr()
plt.figure(figsize =(25,27))
ax = sns.heatmap(torr,annot = True)

NameError: ignored

# EDA - Visualize covid data in Malaysia

In [ ]:
!pip install sweetviz
import sweetviz as sv

my_report = sv.analyze(data)
my_report.show_html() # Default arguments will generate to "SWEETVIZ_REPORT.html"

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize = (12,7))
sns.set_theme(style = 'whitegrid')
sns.countplot(x = 'location', hue = 'new_cases', data = data)

In [ ]:
sns.distplot(x=data['total_cases'], y=data['new_cases'])

In [ ]:
import seaborn as sns
sns.set_theme(style="whitegrid")
ax = sns.violinplot(x="new_cases", y="total_cases", hue="location",
                    data=data, palette="muted", split=True)

In [ ]:
import seaborn as sns
sns.scatterplot(data=data, x="new_cases", y="total_cases",hue='location')
fig, ax = pyplot.subplots(figsize=a4_dims
seaborn.violinplot(ax=ax, data=df, **violin_options)

# Regression using Pycaret

In [ ]:
!pip install pycaret
from pycaret.regression import *

#intialize the setup
exp_reg = setup(data, target = 'new_cases')

                               Description             Value
0                               session_id              5866
1                                   Target         new_cases
2                            Original Data      (101998, 60)
3                           Missing Values              True
4                         Numeric Features                54
5                     Categorical Features                 4
6                         Ordinal Features             False
7                High Cardinality Features             False
8                  High Cardinality Method              None
9                    Transformed Train Set      (68753, 288)
10                    Transformed Test Set      (29436, 288)
11                      Shuffle Train-Test              True
12                     Stratify Train-Test             False
13                          Fold Generator             KFold
14                             Fold Number                10
15                                CPU Jobs                -1
16                                 Use GPU             False
17                          Log Experiment             False
18                         Experiment Name  reg-default-name
19                                     USI              9e97
20                         Imputation Type            simple
21          Iterative Imputation Iteration              None
22                         Numeric Imputer              mean
23      Iterative Imputation Numeric Model              None
24                     Categorical Imputer          constant
25  Iterative Imputation Categorical Model              None
26           Unknown Categoricals Handling    least_frequent
27                               Normalize             False
28                        Normalize Method              None
29                          Transformation             False
30                   Transformation Method              None
31                                     PCA             False
32                              PCA Method              None
33                          PCA Components              None
34                     Ignore Low Variance             False
35                     Combine Rare Levels             False
36                    Rare Level Threshold              None
37                         Numeric Binning             False
38                         Remove Outliers             False
39                      Outliers Threshold              None
40                Remove Multicollinearity             False
41             Multicollinearity Threshold              None
42             Remove Perfect Collinearity              True
43                              Clustering             False
44                    Clustering Iteration              None
45                     Polynomial Features             False
46                       Polynomial Degree              None
47                    Trignometry Features             False
48                    Polynomial Threshold              None
49                          Group Features             False
50                       Feature Selection             False
51                Feature Selection Method           classic
52            Features Selection Threshold              None
53                     Feature Interaction             False
54                           Feature Ratio             False
55                   Interaction Threshold              None
56                        Transform Target             False
57                 Transform Target Method           box-cox

In [ ]:
# Train various ML model and compare using compare_models()
best_model = compare_models()

,Model,MAE,MSE,RMSE,R2,RMSLE,MAPE,TT (Sec)
et,Extra Trees Regressor,348.4428,4.405714e+06,2089.7911,0.9969,0.7193,0.2732,200.848
lightgbm,Light Gradient Boosting Machine,413.4412,5.059117e+06,2226.3011,0.9964,1.7142,4.3528,1.678
rf,Random Forest Regressor,392.3086,5.450789e+06,2322.7713,0.9962,0.2782,0.1684,237.219
gbr,Gradient Boosting Regressor,706.0375,9.882113e+06,3139.7070,0.9931,2.4213,12.3591,47.354
dt,Decision Tree Regressor,535.6619,1.112036e+07,3317.7146,0.9923,0.2789,0.1818,3.796
ridge,Ridge Regression,1212.4800,1.608680e+07,4004.1197,0.9888,3.5906,71.7523,0.188
br,Bayesian Ridge,1214.0513,1.609307e+07,4004.8509,0.9888,3.6090,72.7196,3.273
lasso,Lasso Regression,1216.4549,1.612642e+07,4009.0091,0.9887,3.6134,73.5346,8.707
en,Elastic Net,1294.2389,1.660807e+07,4068.2969,0.9884,3.7812,82.6443,12.132
omp,Orthogonal Matching Pursuit,1205.3234,1.667617e+07,4076.8526,0.9884,3.6217,75.7843,0.229
lr,Linear Regression,1761.3737,2.256804e+07,4686.3373,0.9844,3.9557,108.7657,0.945
llar,Lasso Least Angle Regression,1098.1318,2.407669e+07,4890.4653,0.9833,3.3444,49.9611,0.425
knn,K Neighbors Regressor,1043.0536,4.139365e+07,6400.7969,0.9713,1.3094,1.0646,8.699
ada,AdaBoost Regressor,4691.9150,5.737276e+07,6823.0618,0.9593,5.0161,327.0826,36.856
huber,Huber Regressor,3537.9096,3.963698e+08,19870.6607,0.7250,2.6219,18.2438,15.598
par,Passive Aggressive Regressor,7357.1319,1.918893e+09,37229.6641,-0.4115,4.0770,137.8711,0.742

In [ ]:
# create_model??
dt = create_model('et')

           MAE           MSE       RMSE      R2   RMSLE    MAPE
0     344.0482  4.346443e+06  2084.8124  0.9963  0.7085  0.3905
1     352.2392  5.286306e+06  2299.1968  0.9962  0.6711  0.2399
2     374.5459  4.994766e+06  2234.8973  0.9972  0.7475  0.2667
3     330.0579  3.599742e+06  1897.2986  0.9965  0.7186  0.2862
4     321.3065  3.186654e+06  1785.1202  0.9980  0.7659  0.2472
5     339.3181  4.143273e+06  2035.5032  0.9972  0.7002  0.3365
6     318.0158  3.228938e+06  1796.9247  0.9977  0.7162  0.2763
7     387.9420  5.344016e+06  2311.7129  0.9972  0.6738  0.2408
8     353.9470  5.347445e+06  2312.4543  0.9959  0.7562  0.2094
9     363.0076  4.579559e+06  2139.9904  0.9971  0.7346  0.2389
Mean  348.4428  4.405714e+06  2089.7911  0.9969  0.7193  0.2732
SD     21.4503  8.070193e+05   196.1823  0.0006  0.0307  0.0510

In [ ]:
predict_model(best_model, data)

       iso_code continent  ... excess_mortality    Label
0           AFG      Asia  ...              NaN     1.00
1           AFG      Asia  ...              NaN     0.00
2           AFG      Asia  ...              NaN     0.00
3           AFG      Asia  ...              NaN     0.00
4           AFG      Asia  ...              NaN     0.00
...         ...       ...  ...              ...      ...
101993      ZWE    Africa  ...              NaN  2156.00
101994      ZWE    Africa  ...              NaN  2289.51
101995      ZWE    Africa  ...              NaN  2046.50
101996      ZWE    Africa  ...              NaN   912.00
101997      ZWE    Africa  ...              NaN  1823.22

[101998 rows x 61 columns]

In [ ]:
# Save model
save_model(best_model, model_name='extra-boost-regressor')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=None,
          steps=[('dtypes',
                  DataTypes_Auto_infer(categorical_features=[],
                                       display_types=True, features_todrop=[],
                                       id_columns=[], ml_usecase='regression',
                                       numerical_features=[], target='new_cases',
                                       time_features=[])),
                 ('imputer',
                  Simple_Imputer(categorical_strategy='not_available',
                                 fill_value_categorical=None,
                                 fill_value_numerical=None,
                                 numeric_strate...
                  ExtraTreesRegressor(bootstrap=False, ccp_alpha=0.0,
                                      criterion='mse', max_depth=None,
                                      max_features='auto', max_leaf_nodes=None,
                                      max_samples=None,
                                      min_impurity_decrease=0.0,
                                      min_impurity_split=None,
                                      min_samples_leaf=1, min_samples_split=2,
                                      min_weight_fraction_leaf=0.0,
                                      n_estimators=100, n_jobs=-1,
                                      oob_score=False, random_state=5866,
                                      verbose=0, warm_start=False)]],
          verbose=False), 'extra-boost-regressor.pkl')

In [ ]:
# Load model
model = load_model('extra-boost-regressor')

Transformation Pipeline and Model Successfully Loaded

In [ ]:
# Prediction using loaded model
model.predict(data.tail())

array([2156.  , 2289.51, 2046.5 ,  912.  , 1823.22])